simulator/simulator.go

For certain TPM2 commands like ActivateCredential or PolicySecret, the
TPM is allowed to return TPM_RC_RETRY. In this simulator, this occurs
when dictionary attack prevention mechanisms are used. Specifically,
when checking to see if the maximum number of tries has been exceeded,
the simulator returns TPM_RC_RETRY to let certain values sync to nvdata.
While this can occur on real TPMs as well, it tends not to, and g[o-tpm
does not automatically handle this case](https://github.com/google/go-tpm/issues/59). So we simply remove the above
feature.

Prevent simulator from returning TPM_RC_RETRY

---

README.md
simulator/simulator_test.go
tpm2tools/keys.go
tpm2tools/keys_test.go
tpm2tools/template.go

This package is designed to provide helper methods to make dealing with primary keys easier.
We also update our tests to use these helper functions.

Add tpm2tools

---

internal/test_linux.go
internal/test_windows.go
tpm2tools/keys_test.go

When testing go-tpm-tools on real hardware, I noticed that some operations take much more time to complete than others. There is also a great difference in the amount of time needed between real hardware and virtualized hardware on Google cloud. This PR should make getting performance numbers much easier.
First, a new package called `internal` is added to contain testing helper code (so that we can use it with multiple packages in go-tpm-tools, but external users can't inadvertently bring it in). Then the testing code is cleaned up to use the internal package and benchmarks.
This allows very easy benchmark testing. For example (on Linux):
```bash
-> go test ./tpm2tools -c
-> ../tpm2tools.test -test.bench=. -test.run=^$
goos: linux
goarch: amd64
pkg: …
```

Add testing helpers and benchmarks

---

tpm2tools/keys.go
tpm2tools/seal_test.go

Adds in a library for sealing, unsealing, and resealing with the TPM2.0.
Also adds tests for typical usage of these tools.

Add library for (re|un|)sealing with TPM2.0

---

tpm2tools/keys_test.go

This will let us compare latency for RSA key creation across the three different hierarchies

Add a benchmark for null hierarchy key creations

---

cmd/get_key/get_key.go
tpm2tools/keys.go

This makes it much more simple to get PEM formatted public keys from a
TPM without changing the TPM's state.
A KeyFromNvIndex method is also added which generalizes
EndorsementKeyFromNvIndex to other hierarchies.

Add get_key helper command

---

gotpm/tests/flush_test.go
simulator/simulator_test.go
tpm2tools/close.go
tpm2tools/handles_test.go
tpm2tools/keys.go
tpm2tools/keys_test.go
tpm2tools/seal_test.go

Based off of https://github.com/google/go-tpm-tools/pull/15, but we make the helper public so that the `cmd` tests will also be able to use it.
Tests can now enforce error checking on tpm close.
Tests can now fail if they leak TPM Handles.
Introducing this actually found a bug in [tpm2tools.TestHandles](https://github.com/google/go-tpm-tools/blob/ebf984d5e19b25a44323df04356caf1908a95cd6/tpm2tools/handles_test.go#L17-L40). This bug has been fixed to properly clear the handles.
We also fixed an issue in NewKey that was sometimes not clearing a key.

Introduce CheckedClose

---

simulator/simulator.go

Ideally we would not have warning with compiling the C code with Clang or GCC. Adding these flags fixes most of the problems. Clang still gives a linking warning, but that's an issue with CGO, not this library.

Add flags to prevent warnings

---

tpm2tools/keys.go
tpm2tools/template.go

This change makes it more clear _why_ we set our flags the way we do.
It also makes it easier to later add in ECC-based keys.
This also fixes keys.go to:
- avoid a potential nullptr dereference
- use the Key() and Name() methods from go-tpm
- stop decoding the creationData/tickets, as we don't care about them
@twitchy-jsonp we set the `noDA` flag for our SRK (to not conflict with [what Microsoft does](https://github.com/Azure/azure-iot-sdk-java/blob/39d14a0e7c065f2ed81a9d05199c1f1a6993374e/provisioning/security/tpm-provider-emulator/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMEmulator.java#L41-L52)), and we don't set this flag for our AIK. go-attestation [seems to do the opposite](https://github.com/google/go-attestation/blob/90e37eacce66f4f267b00 …

Cleanup Template and Keys code

---

.gitignore
tpm2tools/handles.go
tpm2tools/keys.go
tpm2tools/keys_test.go

Addresses some of the performance concerns in #24 
The `EndorsementKeyRSA` and `StorageRootKeyRSA` command will now look in the standard locations for a persisted handle, creating one if it does not exist.
The tests all pass against the simulator and a real TPM. I also confirmed that the commands correctly picked up the cached keys on a machine that already had the SRK/EK provisioned. 
This massively improves the time to get an EK or an SRK on a wide variety of platforms:
```
BenchmarkRSAKeyCreation/SRK-Cached-8         	  200000	     11849 ns/op
BenchmarkRSAKeyCreation/EK-Cached-8          	  100000	     13871 ns/op
BenchmarkRSAKeyCreation/SRK-Uncached-8       	     100	  23866486 ns/op
BenchmarkRSAKeyCreation/EK-Uncached-8        	     100	  10798069 ns/op …
```

Support persisting defualt EK-RSA and SRK-RSA

---

gotpm/cmd/flush.go

This allows for `gotpm flush persistent`, allowing a user to clear all of their persisted handles. As this operation only needs to be done rarely, it is not performed when doing `gotpm flush all`.

Support flush with persistent handles

---

simulator/internal/internal.go

These ECC curves are implemented in the standard library, so we should enable them.

Enable NIST P-224 and P-521

---

server/ecc_utils.go
server/key_conversion.go
server/key_conversion_test.go

Expands CreateEkPublicAreaFromKey to support ECC EKs.
Also adds some ECC utility functions.
These changes will be needed to add support for Importing using an ECC EK.

Add ECC EK conversion

---

go.mod
go.sum
server/import.go
server/import_test.go
server/key_conversion_test.go

This change adds support for importing using an ECC EK.
Supports NIST-P224, NIST-P256, NIST-P384, and NIST-P521.

Add support for importing using ECC EKs

---

go.mod
go.sum
server/import.go
tpm2tools/pcr_test.go

Changing HashConstructor to Hash was a breaking change, so I had to fix the couple times it's used.

Update go-tpm version and resolve the HashConstructor breaking change

---

gotpm/cmd/read.go
gotpm/cmd/seal.go
gotpm/cmd/utils.go
tpm2tools/keys.go
tpm2tools/pcr.go
tpm2tools/pcr_test.go
tpm2tools/seal_test.go

Export ComputePCRSessionAuth and add ComputePCRDigest
ComputePCRSessionAuth was modified to take a proto.Pcrs and the hash algorithm used to create the digest.

Refactor of Sealing/Unsealing, expose helper methods

---

simulator/internal/internal.go
tpm2tools/keys.go
tpm2tools/signer.go
tpm2tools/signer_test.go

TpmSigner only supports RSA PKCS#1 v1.5 signing. Subsequent PRs will add PSS and ECC support.
There will also be a PR for adding a (k *Key) GetSigner function, which will check that the Key is appropriate to be used as a Signer.
Also enables SHA512 in the simulator. The simulator told me to set MAX_CONTENT_SIZE to 1360 when I tried to run it after enabling SHA512.

Add TpmSigner 

---

tpm2tools/signer.go
tpm2tools/signer_test.go

As per the crypto.Signer spec, ecdsa signatures are returned in a DER-serialised, ASN.1 signature structure (and is done the same way used in the ecdsa lib).

Add ECC support to tpmSigner

---

cmd/flush.go
cmd/pubkey.go
cmd/root.go

This avoids dumping usage on errors unrelated to usage.

cmd: Set SilenceUsage in PersistentPreRunE

---

.gitignore
files/PKGBUILD
files/boot-unseal.sh
files/initcpio.hooks
files/initcpio.install

This adds Arch Linux support.
We now support installing the binary as well as adding initramfs hooks for unlocking TPM secrets at boot time. This process has some Arch Linux specific components.
Note that incorporating Debian configs is not yet ready (as Debian packaging is much more complex. 
Note that (right now) we use my work PGP key for verifying the package. This allows us to avoid updating sha256 sums every time we bump the package.

Package gotpm for Arch Linux

---

simulator/ms-tpm-20-ref/TPMCmd/tpm/include/TpmProfile.h
tpm2tools/signer.go
tpm2tools/signer_test.go

This change is mostly just writing test code to verify RSAPSS signing works as expected, particularly for salt lengths.

Add PSS support for Signer

---

tpm2tools/handles.go
tpm2tools/keys.go
tpm2tools/keys_test.go
tpm2tools/seal_test.go
tpm2tools/template.go

Certain TPM (the one on my Lenovo X1 carbon) cannot handle CeritfyCreation with a null signing handle correctly. It will throw a TPM_RC_INSUFFICIENT error when we trying to do that.
One work around is that we pass in a non-null signing handle into CertifyCreation.
This PR implement this work around as well as add a ECC AIK template.
AIK ECC key will be cached for performance concerns.
I picked the handle 0x81008FFF (I picked randomly from "Storage -> Available" from Table 11 from  https://trustedcomputinggroup.org/wp-content/uploads/RegistryOfReservedTPM2HandlesAndLocalities_v1p1_pub.pdf

Add ECC AIK template and cache; Work around for CertifyCreation

---

server/import_test.go
tpm2tools/import.go
tpm2tools/keys.go
tpm2tools/keys_test.go
tpm2tools/pcr.go
tpm2tools/seal_test.go
tpm2tools/session.go
tpm2tools/signer.go
tpm2tools/signer_test.go
tpm2tools/template.go

This PR cleans up session handling to make different types of key
authorization easier to use. Refreshing a key's authorization is
now part of each key operation.
We can now sign with keys that need authorization and can Import under
parent keys that don't need authorization.
Tests/comments are updated accordingly.

tpm2tools: Consolidate session handling

---

cmd/read.go
tpm2tools/keys.go

Add a gotpm cmd for tpm2.NVReadEX()
password will be empty and block size will be 0 (which will default to TPM_PT_NV_BUFFER_MAX)

Add read nvdata cmd

---

server/import.go
server/import_test.go
server/key_conversion.go
tpm2tools/import.go

Add importing for RSA signing keys.
The import flow returns a *Key to the user, which can be used to get a tpmSigner to sign digests.

Import RSA signing keys with PCR policies

---

tpm2tools/import.go
tpm2tools/keys.go

If we fail while partially constructing a key, we will leak a handle.
Prevent this by calling Close on failure.

import: Prevent potential handle leak

---

internal/test_other.go
internal/test_tpm.go
internal/test_windows.go

This prevents some flakes we've seen on Linux

internal: Only open the physical TPM once

---

tpm2tools/keys.go
tpm2tools/keys_test.go
tpm2tools/signer_test.go
tpm2tools/template.go

**This is a backwards incompatible change**
We already don't use one for AIK ECC keys, we shouldn't have one for
the RSA keys. Users can still use a nonce if they want by modifying the
template manually.

tpm2tools: Stop using nonce for AIKTemplateRSA

---

tpm2tools/keys.go

We should always read from NVData with the owner authorization.
This is what we do for "gotpm read nvdata", and we should be
consistient. This bug was causing issues when reading endorsement keys
with nvdata templates. 
Bug introduced in #74

tpm2tools: Fix NVReadEx bug

---

tpm2tools/import.go

We were getting a sigsegv because we were returning a nil key. Changed to return the actual key param
Closes #80

Fix error from closing nil key

---

.cirrus.yml
Dockerfile
internal/test_tpm.go
tpm2tools/handles.go
tpm2tools/template.go

When importing internally golint is run. We should also run it
extenrally. This PR also fixes the issues found by golint.

golint: Fixed issues and updated CI check

---

tpm2tools/signer.go

As the hash algorithm is statically determined for the key, we don't
need to require uses to pass the hash algorithm.
We also fix up some error messages to be more style consistent.

tpm2tools/signer: Allow for nil opts to Sign()

---

cmd/flush.go
cmd/open.go
cmd/read.go
cmd/seal.go
go.mod
server/import_test.go
simulator/simulator.go
tpm2tools/import.go
tpm2tools/keys.go
tpm2tools/pcr_test.go

This PR first makes sure that we can inspect the errors returned by go-tpm, even if we wrap them. To do that we use `%w` format specifiers in `fmt.Errorf`, for more info see: https://blog.golang.org/go1.13-errors. This requires raising the minimum Go version to 1.13, but that's fine.
Second, we add tests where Import fails, making sure if fails with the correct error codes.
Finally, we cleanup some nits caught be the linter.

Check that Import gives the correct error codes

---

tpm2tools/signer.go
tpm2tools/signer_test.go

Attempting to use PSSOptions with a non-RSA key results in a segfault
when attempting to access the RSAParameters. Fix this by adding
additional checks. Add a test for this case.

signer: Prevent nil dereference w/ PSSOptions

---

tpm2tools/signer.go
tpm2tools/signer_test.go

This makes it easier to add other signing operations going forward.
This also fixes a bug where we would segfault when using a signing key
with a Null SigScheme. There is now a test to check for this.

Move Alg checks to getSigningHashAlg

---

client/close.go
client/handles.go
client/handles_test.go
client/import.go
client/keys.go
client/keys_test.go
client/pcr.go
client/pcr_test.go
client/seal_test.go
client/session.go
client/signer.go
client/signer_test.go
client/template.go
cmd/flags.go
cmd/flush.go
cmd/flush_test.go
cmd/pubkey.go
cmd/read.go
cmd/seal.go
cmd/seal_test.go
server/import.go
server/import_test.go
server/key_conversion.go
server/key_conversion_test.go
simulator/README.md
simulator/internal/internal.go
simulator/simulator_test.go

Here, I rename the tpm2tools package to client in order to better split up go-tpm-tools along what libraries should be used client-side vs. what should be used server-side. 
I also rename the references to attestation identity key (AIK) to the TPM 2.0 attestation key (AK), #90.

Rename tpm2tools to client and AIK to AK

---

client/pcr.go
cmd/flags.go
cmd/open_other.go
cmd/read.go
cmd/seal.go
proto/pcrs.go

This change also includes some other minor cleanups for the command line tool:
- Formatting of PCRs is improved (to look more like what `tpm2-tools` does)
- Now `gotpm read pcr` and `gotpm seal` can still both use `--hash-algo`, but have different default values
- We now use `/dev/tpmrm0` by default.

Add client.ReadAllPCRs and use it in "gotpm read pcr"

---

client/eventlog.go
client/eventlog_linux.go
client/eventlog_other.go
client/keys.go
client/pcr_test.go
client/quote_test.go
client/seal_test.go
cmd/seal_test.go
internal/test_tpm.go
server/eventlog_test.go
server/verify_test.go

This PR implements multiple testing fixes:
- Only uses PCRs 16 and 23 (to avoid breaking real systems)
- Change `client.GetEventLog` to take the TPM as an argument (allowing the TPM to override the implementation)
- Add tests for `client.Attest`

Improve testing (and add tests for client.Attest)

---

client/handles.go
client/keys.go

This makes it easier to perform attestation, you just do:
```go
tpm, _ := tpm2.OpenTpm()
ak, _ := client.GceAttestationKeyRSA(tpm)
attestation, _ := ak.Attest()
```

Add helper methods for getting the GCE AKs

---

server/eventlog.go
simulator/simulator.go

First, we fix a small bug around `make`
Second, we make it so `simulator.Get()` blocks instead of failing

Fix bugs found when internally importing this ba

---

client/keys.go
client/pcr.go
client/quote_test.go
client/seal_test.go
cmd/seal.go

This will allow us to add functionality to `client.Atttest` in a backwards compatible way.
Note that like many similar Go interfaces (e.g. [`PublicKey`](https://golang.org/pkg/crypto/#PublicKey), [`PrivateKey`](https://golang.org/pkg/crypto/#PrivateKey), [`DecrypterOpts`](https://golang.org/pkg/crypto/#DecrypterOpts), etc...) this `AttestOpts` interface has no methods. This just means we have to use casts to switch functionality, rather than using common methods. 
Also, rename `SealOpt` to `SealOpts` and `CertifyOpt` to `CertifyOpts`. This is the more consistent naming scheme.

Add client.AttestOpts

---

simulator/simulator.go

Double closing the simulator results in mutex being unlocked twice which causes panic. Temporarily make this double closing as a no-op until we fixed the downstream.

Make simulator double close a no-op, as a temp fix

---

client/example_test.go
server/example_test.go

Add examples that pkg.go.dev can pick up.
Add Quote, Import, Attest examples.
Add Seal and Unseal examples.
Add signing examples.
Add ParseAndVerifyEventLog example.
Tested: `godoc -http=:6060` and saw `localhost:6060` carried these examples.

Add example documentation for common uses

---

client/example_test.go
client/keys.go
client/pcr.go
client/seal_test.go
cmd/seal.go

SealOpts was previously an interface that implemented PCRsForSealing.
This did not allow users the option to seal to both a current PCR
selection and a target PCR selection without first reading PCRs manually
and merging into the target. 
CertifyOpts was previously an interface that implemented CertifyPCRs.
This did not allow users the option to seal to both a current PCR
selection and an expected PCR selection without manually reading PCRs
and merging into the target.
These structs allows these use cases more
easily and support future options.

Change SealOpts and UnsealOpts to a struct instead of interface

---

cel/canonical_eventlog.go
cel/canonical_eventlog_test.go
cel/cos_tlv.go

Defined CEL TLV struct, added encoding/decoding functions

Add basic Canonical Event Log(CEL) operations

---

cel/canonical_eventlog.go
cel/canonical_eventlog_test.go

Some ideas about how we might make CEL stuff easier to work with.
@alexmwu @jkl73 what do you think? Worth doing?

cel: Some ideas for ergonomics improvements

---

server/verify.go
server/verify_test.go

Without this change, providing a good AK Cert but a bad AKPub will result in VerifyAttestation succeeding. Now, we check that the AKPub and AKCert (if present) have the same public key.
I also reorganized the code into one `checkAKTrusted` method, which should make things easier to understand.

server: Fix AK Cert checking bug 

---

server/verify.go

Mostly just a style nit
Instead of checking the concrete types for `crypto.PublicKey`, we try to cast the key to an interface containing the expected `Equals` method. This approach is [explicitly mentioned in the `crypto.PublicKey` documentation](https://cs.opensource.google/go/go/+/refs/tags/go1.18beta1:src/crypto/crypto.go;l=154-161).

server: Support all public key types in pubKeysEqual

---

cel/canonical_eventlog_test.go
cel/cos_tlv_test.go
client/pcr_test.go
server/eventlog_test.go
server/verify_test.go

Some tests were failing on some physical TPMs due to certain hash algos are not supported. 
Changing them to SHA1 and SHA256 which most TPM2 chips should support.
Reset the Test PCR for certain tests where requiring the PCR bank to be zero value at the beginning of the test.

Fix tests for physical TPMs

---

client/keys.go
client/keys_test.go
internal/public.go
server/verify.go

Add a SetCert() function to client.Key that allows setting the AK Certificate. The function will verify that the cert matches Key.pubKey.

Add Key.SetCert() function

---

client/attest.go
client/attest_network_test.go
client/attest_test.go

Instead of a boolean flag, have an http.Client specified for fetching AK Certificate chains.

Change FetchCertChain bool option to HTTP client

---

server/verify.go
server/verify_test.go

If an attestation contains intermediate certificates, automatically add them to the options for `checkAKTrusted`

Automatically use attestation intermediates for AK cert verification

---

client/attest.go
client/attest_network_test.go
client/attest_test.go
client/keys.go
client/keys_test.go

Change crypto/x509 dependencies to certificate-transparency/x509 for consistency.
(also avoids attestation verifier tests breaking)

Change crypto/x509 dependencies to ct/x509

---

.gitignore
README.md

Issue was pointed out in https://github.com/google/go-tpm-tools/issues/174#issuecomment-1076825965

Update docs for building gotpm CLI

---

launcher/spec/launcher_spec.go
launcher/spec/launcher_spec_test.go

Create the metadata service field to input service accounts for impersonation.
Operator can leave the field blank, and the default GCE service account will be used;
Or, they can input just one service account which will be the impersonation target;
Or, they can input a list of service accounts, the last service account will be the impersonation target, service accounts before that will act as delegates.
The actual implementation will be in a followup PR

Add impersonate service accounts to launcherspec

---

server/policy_constants.go
server/verify.go
server/verify_test.go

This makes the API easier to call and simplifies our code.
This is a **breaking** change.

server: Use slice of Certificates instead of a CertPool

---

server/verify.go
server/verify_test.go

After validating the AK certificate, look for an extension with a specific ObjectIdentifier that contains GCE instance information and return it in a MachineState.

Retrieve instance info from AK certificate

---

launcher/container_runner.go
server/verify.go
server/verify_test.go

Start to use AK cert in launcher/attestation
Fix ASN1 annotation in `gceInstanceInfo`
Previously it would ignore the optional `gceSecurityProperties` when unmarshaling a real AK cert.

Start to use AK cert in attestation

---

cloudbuild.yaml
launcher/container-runner.service
launcher/entrypoint.sh
launcher/fixup_oem.sh
launcher/preload.sh

Add the basci cloudbuild config and related scripts.
The workflow will build the launcher and install it in a COS image using the cos-customizer.
cos-customizer will also setup the entrypoint script for the machine.

Add cloudbuild config and scripts

---

launcher/container_runner.go

Add the support to restart the container/task based on the metadata by the operator (Alwasy/OnFailure/Never). Default is Never.
Also fixed a errcheck in `measureContainerClaims`.

Add task/container restartability

---

go.work.sum
launcher/attest.go
launcher/attest_test.go
launcher/container-runner.service
launcher/container_runner.go
launcher/container_runner_test.go
launcher/go.mod
launcher/go.sum
launcher/main.go

All launcher log will be sent to Cloud Logging as INFO if running on GCE.
Stdout/Stderr of the container will still be redirected to Stdout/err and won't be sent to Cloud Logging.
Host will poweroff after the launcher exits.
Wrap the `main` function with `run()` so we can call os.exit with non-zero code and execute deferred function.
Update the container io: stdin changed to nil and stdout/stderr will be redirected to logger.

Add Cloud Logging; Update the service file for launcher

---

cloudbuild.yaml
launcher/container-runner.service
launcher/container_runner.go
launcher/main.go
launcher/spec/launch_policy.go
launcher/spec/launch_policy_test.go
launcher/spec/launcher_spec.go

Add the launch policy implementation for env vars and cmd
Update logger so it output everything from launcher to stdout and cloud logging (for better debug)
Update service file so it will sleep for 60 seconds before shutting down the machine.
Update cloudbuild.yaml with the new image name.

Add launch policy for cmd and env vars

---

client/keys.go

We should clearly state that the Key object does not support concurrent access except with the `crypto.Signer` from `GetSigner`. This was found because someone asked why *only* the `tpmSigner.Sign` method allows concurrent accesses.

Update keys.go documentation

---

launcher/agent/agent.go
launcher/agent/agent_test.go
launcher/container_runner.go

This make it easier to build a subset of the code in google3. It
also changes the external API of this package to just be an
interface. This lets us avoid changing our unit tests while also
avoiding code duplication.

Move AttestationAgent code to its own package

---

server/eventlog.go
server/eventlog_test.go

This allows for attestations which do not have a TCG Event Log
to still be processed by VerifyAttestation. Any components of the
MachineState (like SecureBoot state) which depend on these events
will not be present.
This makes our processing more consistent with how we handle the CEL
log. Fixes #162

Properly handle empty TCG Eventlog

---

launcher/verifier/rest/rest.go

We now get better error messages. For example:
No credentials:
```
Getting HTTP Client: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
Credentials, but invalid project:
```
Creating Verifier Client: listing regions in project "confidentialcomputing-e2eee": googleapi: Error 403: Permission denied on resource project confidentialcomputing-e2eee.
Details:
[
{
"@type": "type.googleapis.com/google.rpc.Help",
"links": [
{
"description": "Google developer console API key",
"url": "https://console.developers.google.com/project/confidentialcomputing-e2eee/apiui/credential"
}
]
},
{
"@type": "type.googleapis.com/google.rpc.ErrorInfo",
"domain": "googleapis.com",
"metadata": {
"consumer": …
```

Improve rest.NewClient error handling.

---

cloudbuild.yaml
launcher/container-runner.service
launcher/container_runner.go
launcher/debug.conf
launcher/entrypoint.sh
launcher/hardened.conf
launcher/main.go
launcher/preload.sh
launcher/spec/launcher_spec.go

Remove useLocalImage and serverAddr flags
Add defaultAttestationServiceEndpoint in launcher_spec, and allow
the endpoint to be configured from MDS.
Update launcher service file to support prod and debug images

Update launcher flags and launcher_spec

---

launcher/container_runner.go
launcher/spec/launcher_spec.go

We update the LauncherSpec to store the projectID and region.
The ContainerRunner will now be able to use the REST-based verifier.Client, based on the addr flag.
The flag will determine whether the endpoint is the gRPC or REST verifier. The REST verifier is used if the flag is empty or contains "http", otherwise the gRPC verifier is used.

Update ContainerRunner to use REST verifier

---

launcher/container_runner.go

Print the JSON payload for the OIDC token for the better
debuggability regarding the WIP policy.

Print OIDC token payload

---

.github/workflows/ci.yml

This works around https://github.com/golangci/golangci-lint/issues/2997
and should unblock/fix our CI.

Pin golangci-lint

---

cel/cos_tlv.go
internal/test/test_tpm.go
launcher/agent/agent.go
server/eventlog.go
server/eventlog_test.go
server/verify_test.go

Currently in `getVerifiedCosState` we do two things that are bad from a security perspective:
1. We do not require the CEL events to use PCR 13
2. We skip events that we do not understand (`record.Content.Type != cel.CosEventType`)
(1) is an issue because after a container launchers, we assume that a breakout is possible. So a malicious user can:
- Breakout of a container
- Extend fake events to PCR 14
- Create their own fake CEL eventlog matching the PCR 14 extensions
- Verify an attestation using PCR 14 and this fake CEL eventlog
- Get fake container state to appear in the `MachineState`.
(2) is an issue because the `record.Content.Type` hasn't (yet) been verified in the loop. This means that a malicious user can:
- Breakout of a container
- Modify the CEL log to change the content type …

Be much stricter when processing Attested COS State

---

launcher/container_runner.go

Depends on #246 
Actually measures in the launch separator event.
We probably want to rework when in the container creation/launch process we actually do our measurements, but that can wait for a followup CL, as it isn't security critical, just a defense-in-depth.

Measure LaunchSeparator event

---

cmd/go.mod
cmd/go.sum
go.work
launcher/go.mod
launcher/go.sum

We should have done this right after releasing `v0.3.9` of the main module, but it's not too bad to just do it now. This only was causing issues on go version 1.17 and older.
This change was generated by updating the `go.mod` and `go.work` files and then running `go mod tidy` in each directory.

Update cmd and launcher to use v0.3.9

---

launcher/container_runner.go
launcher/container_runner_test.go
launcher/image/preload.sh
launcher/main.go
launcher/spec/launch_policy.go
launcher/spec/launch_policy_test.go
launcher/spec/launch_spec.go
launcher/spec/launch_spec_test.go
simulator/internal/internal_cgo.go

~~* COS eventlog now can measure to a resettable PCR (in the debug image)~~
~~* Debug PCR will reset every time before launcher run in the debug image~~
* Added a kernel cmdline arg confidential-space.hardened=true to indicate hardened image
* Change LauncherSpec to LaunchSpec
* Add cgo flag to silence deprecate warning in openssl for ms-tpm-20-ref

Add IsHardened in launch spec

---

launcher/container_runner.go
launcher/spec/launch_policy.go
launcher/spec/launch_policy_test.go
launcher/spec/launch_spec.go
launcher/spec/launch_spec_test.go

Operator can pass an MDS variable to turn on/off log redirect
`tee-container-log-redirect`:`true`/`false`
Image author can set a policy to allow/disallow log redirect based on the enviornment (hardened/debug).
`tee.launch_policy.log_redirect`:`debugonly`/`always`/`never`

Add container log stdout/err redirect policy

---

cloudbuild.yaml
launcher/image/preload.sh

This commit enables a dm-crypt layer of encryption with integrity (using authenticated encryption with additional data) on the partition backing /dev/stateful.
This mechanism slows down boot by ~1min.
The key is stored in memory, and, as a result, the writable, "stateful" partition is wiped on subsequent boots.
Ran `./run_cloudbuild.sh debug` in test project.
Created vm from output image.
Examined serial log of the VM:
```
[[0;32m  OK  [0m] Finished [0;1;39mWait for Network to be Configured[0m.
[    8.024822] protect-stateful-partition.sh[157]: WARNING: Device /dev/sda1 already contains a 'ext4' superblock signature.
[    8.029283] protect-stateful-partition.sh[157]: Existing 'ext4' superblock signature (offset: 1080 bytes) on device /dev/sda1 will be wiped.
[    8.034254] …
```

Integrity-protect stateful partition on CS image

---

launcher/image/test/README.md
launcher/image/test/check_failure.sh
launcher/image/test/cleanup.sh
launcher/image/test/create_vm.sh
launcher/image/test/data/echo_startupscript.sh
launcher/image/test/test_hardened_cloudbuild.yaml
launcher/image/test/test_startupscript_disabled.sh
launcher/image/test/util/read_serial.sh

Add a Cloud Build-based integration test for the launcher image against startup script disablement.
Tested against hardened and debug image:
Hardened
```
Step #3: Already have image (with digest): gcr.io/cloud-builders/gcloud
Step #3: Checking the status.txt file for test results:
Step #3: No status.txt file found.
Finished Step #3
```
Debug
```
Starting Step #3
Step #3: Already have image (with digest): gcr.io/cloud-builders/gcloud
Step #3: Checking the status.txt file for test results:
Step #3: TEST FAILED
Step #3: The test failed for build f222c383-a2df-406f-9f88-1bf9886856af.
Finished Step #3
```

launcher: Integration test startup script on image

---

go.work.sum
launcher/container_runner.go
launcher/container_runner_test.go
launcher/go.mod
launcher/go.sum

Currently, the token refresher stops after one attempt at refreshing the attestation verifier OIDC token.
Here, we use exponential backoff to retry refreshing the attestation verifier.
After the retries, the refresher goroutine stops.

launcher: Retry OIDC token refresh with backoff

---

go.work.sum
launcher/go.mod
launcher/go.sum
launcher/launcher/main.go
server/verify.go
server/verify_test.go

Fix #264 and #263 
Catch panic using defer recovery in launcher.
Return an empty MachineState pointer instead of nil in validateAKCert.

Fix panic catching in launcher and AKCert

---

launcher/container_runner.go
launcher/container_runner_test.go

We want the retry to occur ~hourly (with jitter), as this will match the normal refreshed requests. This allows the launcher to provide a token even with long service outages.
Also, jitter on the refresh duration allows smearing of requests in the event many clients come online at similar times after an outage. Without this, load on the service side would be less balanced over time.

launcher: Change retry policy to hourly and add jitter to refresh time

---

client/attest_test.go
go.mod
go.sum
server/verify_sev.go
server/verify_test.go

This adds the ability for the test to run with a real sev-guest device, not just a fake.
Tested internally on real hardware.

Update to go-sev-guest v0.4.1

---

cloudbuild.yaml
launcher/image/preload.sh

The systemd default timeout is 90s. This is often insufficient for standing up the protected stateful partition, which relies on writing dm-integrity tags for integrity protection. This can fail due to PD throttling on smaller disks and a machine that reboots multiple times. Additionally, this makes the debug image more usable on non-Confidential VM machines (which often have fewer/timeshared vCPUs).
We benchmarked an upper bound for the timeout on GCE, around 900s.
This also pins the COS version to an older version of cos-dev, as the current version is broken.
tested on GCE with a workload that continues to restart. left it running for several hours without observing an issue (booted >90 times).

Increase default systemd wait timeout to 900s

---

go.mod
go.sum

This includes the bugfix to error types that broke the internal import.

Update to go-sev-guest v0.4.5

---

go.mod
go.sum
server/verify.go
server/verify_sev.go
server/verify_test.go

The trust API has changed a little to allow the fake KDS implementation to work appropriately. The "bad root" tests that swap around certs were broken since the default root didn't have any x509 certs to swap. That has been fixed in v0.5.0.

Upgrade to go-sev-guest v0.5.0

---

launcher/auth.go
launcher/container_runner.go
launcher/container_runner_test.go
launcher/launcher/main.go

Now can pull images with an access token from GCP gcr.io or artifact registries.
Also can pull images without a token from the public docker.io registry.

[launcher] Fix image pulling in launcher

---

cloudbuild.yaml
launcher/image/test/test_debug_cloudbuild.yaml
launcher/image/test/test_hardened_cloudbuild.yaml
launcher/image/test/test_launcher_workload.sh

This allows us to verify the test workload is properly seeing the env and cmds the operator passes in.

test: Override test workload env vars and cmd

---

.gitignore
cloudbuild.yaml
launcher/image/test/scripts/test_launchpolicy_cmd.sh
launcher/image/test/scripts/test_launchpolicy_env.sh
launcher/image/test/scripts/test_launchpolicy_log.sh
launcher/image/test/test_debug_cloudbuild.yaml
launcher/image/test/test_hardened_cloudbuild.yaml
launcher/image/test/test_launcher_workload.sh
launcher/image/test/test_launchpolicy_cloudbuild.yaml
launcher/image/test/test_mds_var_change.sh
launcher/image/test/util/change_metadata_vars.sh
launcher/image/testworkloads/basic/Dockerfile
launcher/image/testworkloads/basic/main.go
launcher/image/testworkloads/launchpolicycmd/Dockerfile
launcher/image/testworkloads/launchpolicylog/Dockerfile

* Add the source for the basic-test image used in our integ tests.
* Check the OIDC claims in the token match what we expect.
* Check MDS variable change has no effect once the workload kicks off.
* Add launch policy tests against: cmd overrides, environment variable overrides, and logging redirection.

test: Add test workload code, check OIDC claims, and validate launch policy checks

---

simulator/simulator.go

The `Write` function returned the number of bytes written to the internal command response buffer. Depending on the type of command executed against the TPM, this would usually result in a different number of bytes being written than the original input.
The fix is useful if one wants to wrap the `io.ReadWriterCloser` functions with implementations that perform strict checks. An example is using an `io.MultiWriter` to capture the bytes sent to the TPM for debugging purposes, which will fail if the number of bytes written does not equal the original length of the input bytes.

Return the actual number of bytes written to through command buffer

---

CONTRIBUTING.md
README.md
RELEASING.md

This should hopefully reduce errors when cutting new releases
of go-tpm-tools and related submodules.
I'll wait until #186 is done before merging this, as we should make sure the instructions work properly.

Add RELEASING instructions

---

cmd/open.go

Add extTPMWrapper so the CMD package can call EventLog() in a test.

Add a wrapper for ExternalTPM

---

launcher/image/test/test_debug_unstable_cloudbuild.yaml
launcher/image/test/test_hardened_unstable_cloudbuild.yaml
launcher/image/test/test_os_config_os_policy.sh

Currently, OS Policy assignment rollout does not finish in a timely manner. These tests are part of "unstable" cloudbuilds until this is resolved.

Add OS Policy assignment tests for both debug and hardened.

---

go.mod
go.sum
server/verify_sev.go

This new version includes more reliability measures with respect to host throttling and AMD KDS clock drift causing certificate verification failure.

Update to go-sev-guest v0.6.0

---

cmd/attest.go
cmd/attest_test.go
cmd/flags.go
cmd/verify_test.go

Added --tee_technology flag in attest CLI that specifies the type of hardware the user wants to use for attestation.

add tee_technology flag and test for tee_technology flag

---

go.mod
go.sum

This is a minor robustness update to work around distributions using kernel >= 5.19 and < 6.1.

Update go-sev-guest to v0.6.1

---

client/import.go
client/keys.go
client/keys_test.go
client/session.go

Implementation for https://github.com/google/go-tpm-tools/issues/237.
As discussed in the issue, I exposed the different sessions to be able to set it in the loaded key.
If you don't want to expose all possible sessions, exposing just the `NullSession` is sufficient for our use-case.

Allow loading of cached keys

---

.github/workflows/releaser.yaml
.goreleaser.yaml

The CLI binary is a useful artifact to have prebuilt and ready to use. This action ensures that all new releases that get cut will have the binary artifacts ready for download for the tableau of supported OSes and architectures.

Add GoReleaser release action for gotpm CLI

---

launcher/spec/launch_spec.go
launcher/spec/launch_spec_test.go

Add a new metadata flag to launchSpec such that container launcher knows the locations of signed container images.

Add a new metadata flag of signedImageRepos

---

launcher/container_runner.go
launcher/container_runner_test.go

Exporting the filepath and filename will allow the attestation token file to be referenced by other libraries that need it (ex. STET)

Export attestation token filepath and filename

---

launcher/container_runner.go

Increase the max file descriptor (nofile) for the container process from 1024 to 131072.
Check the container process limit, can see the updated number (Max open files):
OLD
```
$ cat /proc/1102/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             unlimited …
```

[launcher] Increase the max file descriptor

---

launcher/container_runner_test.go

This reverts commit 4a3d6e75a009f647fdc6bb386111d950f2d5ccf3. This commit has made our CI flakey, and we do not need to enable this test internally in g3.

Revert "Decrease MaxElapsedTime for retry backoff in tests (#337)"

---

go.mod
go.sum
server/verify_tdx.go

The go-tdx-guest library has renamed the function name TdxVerify to TdxQuote. Therefore, the server package has been updated to reflect these changes.

Rename TdxVerify function to TdxQuote in server package.

---

launcher/container_runner.go
launcher/container_runner_test.go
launcher/launcherfile/launcherfile.go

This pulls out consts in container_runner.go used by different packages.

Add launcherfile package for path and file consts

---

go.mod
go.sum

Importing the latest version of go-tdx-guest library in which client_windows.go file is added.

import go-tdx-guest v0.2.2

---

launcher/image/test/scripts/test_launcher_workload_cloudlogging.sh

The basic workload cloud logging test does not have some wait time for the workload to write to cloud logging, so it consistently fails.

Fix flakey cloud logging test

---

launcher/container_runner.go
launcher/image/cloudbuild.yaml
launcher/image/preload.sh
launcher/internal/experiments/experiments.go
launcher/internal/experiments/experiments_test.go
launcher/launcher/main.go
launcher/spec/launch_spec.go

Add experiment support.
This change:
- pulls the experiment binary from a GCS bucket (not open-sourceable code)
- gets metadata from the MDS for the experiment binary (image family, image version, git commit hash for presubmit images)
- calls experiment binary with metadata fetched
- the binary fetches the project id + vm instance ID from the metadata server
- provides experiment data as a map in the launch spec
- provides helper functions to make the launch spec map type-safe

Add experiment support

---

launcher/launcher/main.go

This PR:
Updates main.go to create the directory where experiments data is saved for the script before it is called.
Fixes experiment-related log messages to be in the correct format

Make launcher host tmp directory before experiment fetch

---

launcher/image/fixup_oem.sh
launcher/image/preload.sh

Previously, we would need to pull logs from the server to see how exactly the cmdline gets passed through. This is because the cmdline passed by GRUB, and as a result, measured in the TCG event log, has surrounding quotes stripped out.  So, we mutate the existing command line to what GRUB passes to the kernel.

launcher: Print kernel cmdline on builds 

---

launcher/internal/oci/cosign/signature.go
launcher/internal/oci/cosign/signature_test.go
launcher/internal/signaturediscovery/client.go

From https://github.com/google/go-tpm-tools/blob/main/launcher/agent/agent.go#L105 https://screenshot.googleplex.com/7wxmTBPQubwZLoB, the launcher prints golang objects for any found signatures, we should print signature details instead.

Container launcher prints signature details instead of signature object

---

cloudbuild.yaml
launcher/image/test/scripts/test_experiment_value.sh
launcher/image/test/test_experiments_client.yaml
launcher/image/test/util/read_serial.sh
launcher/spec/launch_policy.go

Adds image tests for the experiments binary
Tests added:
- VM started, LaunchSpec has the TestFeature enabled
Tests still needed:
- VM started, binary is replaced with a failing binary, LaunchSpec has the TestFeature disabled
- VM started, binary is replaced with binary that writes random experiments, LaunchSpec has the TestFeature disabled

Add image tests for the experiments binary

---

cloudbuild.yaml
launcher/image/test/scripts/test_launcher_workload_discover_signatures.sh
launcher/image/test/test_discover_signatures.yaml

Added CloudBuild steps for both hardened image and debug image to run signature discovery tests:
1. use cosign to sign the container,
2. launch a VM with signed container image support,
3. check VM serial logs for any found signatures.

Add CloudBuild steps to run image tests against the signatures discovery feature

---

launcher/launcher/main.go

The previous fix in https://github.com/google/go-tpm-tools/pull/384 was incomplete due to variable scoping. Moving OS exit into a function to be called at exit allows exitCode variable to be referenced at that time, instead of when the defer statement was called.

Handle launcher exit code checking during deferral evaluation

---

launcher/image/exit_script.sh
launcher/image/test/scripts/test_mds_var_change.sh
launcher/image/test/test_debug_cloudbuild.yaml
launcher/image/test/util/read_serial.sh

Add a test to check VM remain alive after workload exit in a CS debug VM.
The test currently is failing as expected. Once #392 is merged, the new test here should pass.

[launcher] Add test to check VM alive

---

cmd/attest_test.go

This resulted in failing tests on real GCE VMs that already have the AK template. A real testcase is a better suited for integration tests instead of unit tests anyway.
Failure:
```
sudo /var/lib/google/cmd_nocgo.test -tpm-path /dev/tpmrm0
Error: failed to collect attestation report : provided nonce must not be empty
...
Error: verifying attestation: failed to verify quote: quote extraData [18 52] did not match expected extraData [67 33]
--- FAIL: TestVerifyWithGCEAK (0.01s)
--- FAIL: TestVerifyWithGCEAK/gceAK:RSA (0.00s)
attest_test.go:65: NVDefineSpace failed: error code 0x4c : NV Index or persistent object already defined
--- FAIL: TestVerifyWithGCEAK/gceAK:ECC (0.00s)
attest_test.go:65: NVDefineSpace failed: error code 0x4c : NV Index or persistent object already defined
Error: failed …
```

Skip tests that call setGCEAKTemplate

---

simulator/ms-tpm-20-ref/TPMCmd/tpm/include/LibSupport.h

- This pr add RISC V compilation support for `Microsoft TPM2 Simulator`.
- Tested on `Arch Linux : Sophgo Mango : rv64imafdc`

Add RISC V support

---

.github/workflows/ci.yml
cloudbuild.yaml
launcher/agent/agent.go
launcher/agent/agent_test.go
launcher/container_runner.go
launcher/container_runner_test.go
launcher/image/test/scripts/test_launcher_workload_discover_signatures.sh
launcher/image/test/test_discover_signatures.yaml
launcher/image/test/test_oda_with_signed_container.yaml
launcher/internal/experiments/experiments.go
launcher/teeserver/tee_server.go
launcher/teeserver/tee_server_test.go

Discussed offline, we decide to introduce container signatures cache to attestation agent.
So we should refresh the signatures cache every time the token refresher goroutine runs (~1/hr), and ODA will only read from the cache.
This PR also includes the following changes:
- fixes teeserver context reset issue
- removes the existing experiment flag `EnableSignedContainerImage`, add a new flag `EnableSignedContainerCache`

Fix teeserver context reset issue & add container signature cache

---

client/attest_test.go
cmd/attest.go
cmd/flush.go
cmd/pubkey.go
cmd/read.go
cmd/root.go
cmd/seal.go
cmd/verify.go
launcher/agent/agent_test.go
launcher/internal/systemctl/systemctl_test.go
launcher/teeserver/tee_server_test.go

golangci-lint just got updated to version `v.1.56.1` https://golangci-lint.run/product/roadmap/#v1561 and started to fail with `unused parameter` error.
This PR is a quick fix to set all unused parameters as `_`

Set all unused parameters as `_` to fix CI lint failure

---

launcher/image/preload.sh
launcher/image/test/create_vm.sh
launcher/launcher/main.go

The Confidential Space image now uses dm-crypt with a backing dm-integrity where the integrity tags are stored in memory vs getting interleaved on the actual disk.
This changes comes with support for boot-time integrity tag initialization speed up and automatically resizing of the stateful partition on the boot disk.

Use resizable integrity-fs with in-memory tags

---

launcher/image/testworkloads/customtoken/happypath/main.go

The customtoken test reaches out to the attestation service and tries to read the resulting JWT. It regularly fails with `jwt.ValidationErrorNotValidYet` since there may be clock skew between the service and the running VM.

Make customtoken test sleep to mitigate clock skew

---

go.mod
go.sum
go.work.sum

Update go-tdx-guest version to v0.3.1 which includes -
1. go-configfs-tsm moved from go-tdx-guest to its separately managed git repo.
2. Logging added to client package for QuoteProvider/Device.
3. Updated TCB Info verification logic.

Update go-tdx-guest version to v0.3.1

---

.goreleaser.yaml

Built using `goreleaser build --snapshot`
```
$ ls dist
artifacts.json         gotpm_darwin_arm64    gotpm_windows_amd64_v1
config.yaml            gotpm_linux_amd64_v1  gotpm_windows_arm64
gotpm_darwin_amd64_v1  gotpm_linux_arm64     metadata.json
$dist/gotpm_linux_amd64_v1/gotpm attest --tee-technology blah
Error: tee-technology should be either empty or should have values sev-snp or tdx
$ldd dist/gotpm_linux_amd64_v1/gotpm  
not a dynamic executable
```

Statically link binaries built by goreleaser

---

cmd/token.go
internal/util/util.go
internal/util/util_test.go
launcher/agent/agent.go
launcher/agent/agent_test.go
verifier/fake/fakeclaims.go
verifier/fake/fakeverifier.go

We inadvertently dropped the launcher's canonical event log when refactoring in #419. This fix adds back the launcher CEL and adds a unit test that checks for CEL measurements in the MachineState.
2024/04/12 18:01:17 Refreshed container image signature cache: [0xc00030e260 0xc00030e280]
2024/04/12 18:01:17 Found container image signatures: [0xc00030e260 0xc00030e280]
--- FAIL: TestAttest (0.00s)
--- FAIL: TestAttest/all_experiment_flags_disabled (0.17s)
/Users/wuale/Projects/go-tpm-tools/launcher/agent/agent_test.go:389: got image ref , want image ref gcr.io/fakeRepo/fakeTestImage:latest
/Users/wuale/Projects/go-tpm-tools/launcher/agent/agent_test.go:392: got image digest , want image digest sha256:adb591795f9e9047f9117163b83c2ebcd5edc4503644d59a98cf911aef0367f8 …

Fix bug dropping CEL in launcher attestations

---

client/keys.go

It seems this check was not valid for a while. This PR fixes that and restores unsealing for the old devices.

fix invalid check and restore workaround from #72

---

client/signer.go

The error message should return the length of the digest to compare against the length of the hash, instead of returning the whole digest.

Error message should return length of digest

---

cmd/token.go
go.work.sum
internal/util/util.go
internal/util/util_test.go
launcher/agent/agent.go
launcher/agent/agent_test.go
launcher/container_runner.go
launcher/container_runner_test.go
launcher/teeserver/tee_server_test.go

**Breaking Change**
`CreateAttestationAgent()` now returns an error in addition to the agent object
Concurrent http requests will exhaust TPM transient handle (3), adding a mutex to handle the requests one by one.
The AK key in the agent will now only be fetched once and saved to the struct.
Tested on a GCE VM, "failed to get AK: warning code 0x2 : out of memory for object contexts" error no longer appears

[launcher] Fix a concurrent TPM access issue

---

.github/workflows/ci.yml
.github/workflows/releaser.yaml
simulator/internal/internal_cgo.go

Root cause:
macos-latest no longer gives us an amd64 machine to build and run our test (even if we ask for an amd64 machine specifically, I tested using uname, and it's still a arm64 mac)
https://github.com/actions/runner-images/tree/main
Changes:
* Specifically add `macos-latest/arm64` to the build/test
* Add `macos-14-large` which supports amd64
* Adding openssl lib location (homebrew) for `darwin/arm64`
* Remove `macos-latest` from releaser file, as we don't need to run the releaser in different OSes. And since `gotpm` binary doesn't need the simulator CGO support, the linux should handle the cross compilation for all platform/arch when doing the release. This should also fix the error when we creating a release (because we were trying to release the same binary twice)

Fix releaser.yaml and ci.yml file on macos

---

launcher/container_runner.go
launcher/internal/signaturediscovery/client.go
launcher/internal/signaturediscovery/client_test.go
launcher/launcher/main.go
launcher/registryauth/auth.go

Currently we only fetch the VM SA once, for the purpose of downloading workload image from Artifact registry.
But it doesn't work well for long running workloads because the VM SA token will expire after 1 hr, and thus lead to 401 errors when the signaturediscovery client tries to fetch image signatures periodically.
We'll need to refresh the resolver for signaturediscovery client to authenticate with the target docker repo before fetching container signatures.
- move `auth.go` to from package `launcher` a to a new sub-package `github.com/google/go-tpm-tools/launcher/registryauth` so that auth utilities can be used cross packages. Add a new method that takes in a metadata server client and returns a refreshed remote resolver.
- refactor of signaturesdiscovery client to be able to refresh …

Refresh SA auth token in signaturediscovery client before fetching container image signatures

---

cloudbuild.yaml
cmd/gotpm/main.go
launcher/image/cloudbuild.yaml
launcher/image/preload.sh
launcher/image/test/test_memory_monitoring.yaml
launcher/launcher/main.go

* gotpm cmd can now shows version info:
```
$ go-tpm-tools_linux_amd64_v1/go-tpm-tools -v
gotpm version 0.4.4, commit 2dca42d8bece8ce657cd972d4451e3ba803b8e96, built at 2024-05-22T20:46:34Z
- go-sev-guest version v0.3.1
- go-tdx-guest version v0.9.3
```
* launcher will also show build commit in the welcome message.
* update launcher cloudbuild to go1.21 to match its go.mod
* add "sync" at the end of the `preload.sh` file to fix (hopefully) the empty files in OEM partition when building the image.
```
/usr/share/oem/confidential_space $ ls -althr
total 80M
drwxr-xr-x 4 root root 4.0K May 28 20:51 ..
-rwxr-xr-x 1 root root  55M May 28 20:51 confidential_space_experiments
-rwxr-xr-x 1 root root  26M May 28 20:51 cs_container_launcher
-rw-r--r-- 1 root root    0 May 28 20:51 …
```

Add version information and fix cloudbuild

---

cmd/flags.go
cmd/token.go
cmd/token_test.go
verifier/util/fake_attestation_server.go

- add a custom-nonce flag to allow user supplied string array for Custom Nonce
- added the flag in token subcommand for generating tokens with the custom nonce field
- added the flag in unit test

add custom nonce flag to cmd package token subcommand

---

launcher/cloudbuild.yaml
launcher/image/test/test_oda_with_signed_container.yaml
server/verify.go
server/verify_test.go

This PR includes changes to populate the machinState proto with the verified SNP/TDX attestation data. The attestation verifier service will leverage the verified machineState to make claims around.
- Unexport `verifyGceTechnology` because GCETechnology event log is closely related to TPM, this function is directly called after the event log is parsed.
- Use a stable COS image version `cos-dev-117-18374-0-0` rather than the latest COS image version to avoid CS image build issues.

Populate the SNP/TDX Machine State field with the verified SNP/TDX attestation data + use a stable COS image version

---

launcher/image/test/util/read_serial.sh

I noticed some test is blocked on read serial on an already stopped VM. So creating a case to catch that.
Return the serial log immediately instead of waiting for full 10mins in that case. This shorten the overall cloudbuild time from 50mins to 24mins.

[launcher] Optimize serial read in test

---

launcher/cloudbuild.yaml

latest cos dev image has constant network interface issue (probably due to using new 6.6 kernel).
It's time for CS to base on a more stable and supportive release track.
Current latest build is on [cos-dev-117-18374-0-0](https://cloud.google.com/container-optimized-os/docs/release-notes/dev#cos-dev-117-18374-0-0_)
we will switch to 113 track [cos-113-18244-85-49](https://cloud.google.com/container-optimized-os/docs/release-notes/m113#cos-113-18244-85-49_)

[launcher] Switch base image to 113 cos

---

go.work.sum
launcher/cloudbuild.yaml
launcher/container_runner.go
launcher/image/test/test_log_redirection.yaml
launcher/image/test/test_mounts.yaml
launcher/image/testworkloads/mounts/Dockerfile
launcher/image/testworkloads/mounts/print_mounts.sh
launcher/internal/launchermount/mount.go
launcher/internal/launchermount/tmpfs.go
launcher/internal/launchermount/tmpfs_test.go
launcher/spec/launch_policy.go
launcher/spec/launch_policy_test.go
launcher/spec/launch_spec.go
launcher/spec/launch_spec_test.go

CS operators can use tee-dev-shm-size to increase the size of the /dev/shm mount for the workload.
CS operators can use `tee-mount` to specify tmpfs mounts in the running container. For example: `type=tmpfs,source=tmpfs,destination=/tmp;type=tmpfs,source=tmpfs,destination=/tmp2,size=12345`.
This interacts with the `tee.launch_policy.allow_mount_destination` launch policy that configures what the allowable mount points for a given workload are.

[launcher] Add configurable /dev/shm size and tmpfs mount option

---

cmd/token.go
verifier/rest/rest.go
verifier/rest/rest_test.go

This PR introduces the following changes:
- Convert tdx quoteV4 proto from go-tdx-guest repo to API protos such that new confidentialcomputing client library can understand.

Use confidentialcomputing api v1.6.0 to send TDX attestation

---

launcher/agent/agent_test.go

This is failing unit tests sometimes: 
=== RUN   TestFetchContainerImageSignatures_RetriesOnFailure/two_repos,_no_failures
fatal error: concurrent map writes
fatal error: concurrent map writes

Add mutex to failing client to prevent concurrent writes

---

.github/workflows/ci.yml
launcher/agent/agent.go
launcher/agent/agent_test.go
launcher/container_runner.go
launcher/container_runner_test.go
verifier/rest/rest_test.go

Instantiate a new backoff object per goroutine since the current retry library is not thread-safe.
This PR also adds those tests related to `RefreshToken` + `FetchContainerSignatures` to a test suite with race condition check.

Instantiate backoff strategy per goroutine

---

launcher/container_runner.go

Previously, port opening only works on IPv4 traffic, now enabling it for IPv6 as well.

[launcher] launcher can expose IPv6 ports as well

---

verifier/rest/rest.go

This will make it a bit easier to find which service failed when investigating machine failures. Currently you need to look around for other logs that specify which region the machine is in, which is annoying.
Ideally in the future we have some sort of ID from the service to be able to easily identify logs on the service side.

Add the location of the service we are calling to the API error logs

---

client/pcr_test.go
launcher/container_runner.go
launcher/launcher/main.go
launcher/util.go
launcher/util_test.go

Log TPM dictionary attack related info for debugging.
Also update the TPM lockout params before launching the workload (if it's not set to the default):
max tries : 3 -> 32
interval  : 1000 seconds -> 0x1C20 (120 mins)
lockout recovery : 1000 seconds -> 0x15180 (24 hrs)

[launcher] Add DA lockout params when launching

---

launcher/container_runner.go
launcher/launcher/main.go

We currently rely on the random OOM Killer to delete processes when we have out of memory issues. This can lead to nondeterministic and potentially exploitable behavior where the OOM Killer can delete other sensitive processes. This change now makes the container workload a very likely candidate for the OOMKiller when the CS VM is experiencing out of memory issues.
```
wuale@cs-dbg-241000 ~ $ ps -ef --forest
root        1238       1  0 04:54 ?        00:00:00 /usr/bin/containerd-shim-run
root        1258    1238  0 04:54 ?        00:00:00  \_ nginx: master process ng
101         1295    1258  0 04:54 ?        00:00:00      \_ nginx: worker proces
101         1296    1258  0 04:54 ?        00:00:00      \_ nginx: worker proces
wuale@cs-dbg-241000 ~ $ cat /proc/1258/oom_score_adj
-998 …
```

Change container workload's default OOM Score

---

launcher/internal/healthmonitoring/nodeproblemdetector/systemstats_config.go

Based on security review recommendations, we should be conservative about which metrics we enable in NPD. This reduces the full list of supported metrics to a smaller one.

Reduce NPD full config

---

launcher/agent/agent.go
launcher/agent/agent_test.go
verifier/client.go
verifier/fake/fakeverifier.go
verifier/oci/cosign/fakesignature.go
verifier/rest/rest.go

OCI signatures are converted to a different structure in the Rest client for GCA. With the addition of ITA, we want to send a similar structure, so the conversion should be done at a higher level - the agent - rather than being verifier-specific.
The verifier client package will have its own `ContainerSignature` type - which contains only the fields that will be sent to verifier services - rather than using the full `oci.Signature` object.
`fakesignature` is also updated to remove implementations for `PublicKey` and `SigningAlgorthm` since the corresponding `fakeverifier` will use the new `ContainerSignature` type that lacks these methods. Instead, `fakeverifier` will parse the pubkey and sigalg from the payload - similar to how this is done in the actual verification process.
- In …

Add ContainerImageSignature type to verifier client

---

cmd/go.mod
cmd/go.sum
go.mod
go.sum
launcher/go.mod
launcher/go.sum
verifier/go.mod
verifier/go.sum

go-tpm-tools currently uses go-sev-guest at v0.11, however as the CPUID information added in AMD version3 is populated, this will lead to a failure when collecting SNP attestation using `go-tpm-tools` with the error 
```
mbz range [0x188:0x1a0] not all zero: 190101000000000000000000000000000000000000000000
```
The `ReportVersion3` support (see PR https://github.com/google/go-sev-guest/pull/141) was introduced to go-sev-guest since v0.12.0 , now bumping the go-sev-guest version.

Bump go-sev-guest to v0.12.1

---

LICENSE

This repo vendors the Microsoft simulator code, not the IBM copy of the Microsoft simulator code. See discussion at https://github.com/google/go-tpm-tools/issues/533
This change also includes a reference to Intel's BSD license in that same project.
Fixes #533

Update the LICENSE to accurately describe the simulator

---

server/eventlog.go
server/eventlog_test.go

Current grub parsing logic considers both GRUB null terminator cases (we check the hash digest on both raw data with or without the "\x00" byte)
There is a possibility for someone to append a random byte (not \x00) at end of the raw data in the eventlog. The random byte won't be included in the digest verification, but will show up as a piece of verified raw data.
When we add the raw data to the struct, we always include "\x00" byte if it exists in raw data. This might causing confusion since the raw data in our struct might not exactly match the hash digest. User needs to remove the null terminator from the raw data manually if they want to use it.

Fix a grub eventlog parsing issue with null terminator

---

.github/workflows/releaser.yaml

The defaults of goreleaser v3 are deprecated.

Update releaser actions.

---

go.work.sum
launcher/image/preload.sh
launcher/internal/gpu/config.go
launcher/internal/gpu/driverinstaller.go
launcher/internal/gpu/driverinstaller_test.go

This PR contains the following changes:
- Adds the verification of driver (nvidia .run file) digest in driver installation flow.
- Reads the run file digest from well known public GCS bucket and stores it under OEM partition as reference driver digest.
- Required utility functions for parsing and hash calculation.  
**Testing:**
- Existing image tests for confidential GPU ran successfully.
- Unit tests for newly added functions
**Changes which would be part of follow-up PR:**
- Measure GPU CC mode status.

Add driver digest verification in confidential GPU driver installation flow

---

launcher/image/test/test_gpu_driver_installation_cloudbuild.yaml

Image build fails because of the stockout error for zone `us-west1-b`. This PR moves the tests to different zone.
```
Step #4 - "CreateTDXCVMWithNonConfidentialGPU": ERROR: (gcloud.compute.instances.create) Could not fetch resource:
Step #4 - "CreateTDXCVMWithNonConfidentialGPU": ---
Step #4 - "CreateTDXCVMWithNonConfidentialGPU": code: ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS
Step #4 - "CreateTDXCVMWithNonConfidentialGPU": errorDetails:
Step #4 - "CreateTDXCVMWithNonConfidentialGPU": - help:
Step #4 - "CreateTDXCVMWithNonConfidentialGPU":     links:
Step #4 - "CreateTDXCVMWithNonConfidentialGPU":     - description: Troubleshooting documentation
Step #4 - "CreateTDXCVMWithNonConfidentialGPU":       url: https://cloud.google.com/compute/docs/resource-error
Step #4 - …
```

Update zone for CGPU image tests

---

testutil/utils.go

Adds a wrapper package around internal test functions as our need for testing outside of this repo expands.
Since `GetTPM` makes use of a package-level lock in `internal/test`, it is better to wrap the function than move it to a new package (same for any future functions in that package we also want to make available).

Add testutils package to make select test helpers publicly available

---

server/verify.go
server/verify_test.go
verifier/fake/fakeverifier.go

This PR removes the Attested COS state specific CEL parsing logic which would help us use the `VerifyAttestation` method for the clients who wants to parse the CEL differently. This PR keeps the `ParseCOSCELPCR` method (under `eventlog.go`) as is if existing client want to use it. 
It updates the implementation of fake verifier with additional logic of parsing COS state. This would make agent tests (in launcher) continue to work without any issue. 
**Testing:**
- Unit tests of server package passed successfully.
- Successfully built the gotpm library.

Remove Attested COS specific CEL parsing logic

---

client/attest.go
internal/quote.go
server/verify.go
server/verify_test.go

Currently, key.Attest takes a slice of data for the attestation nonce. This gets passed directly to the TPM. However, verifiers that are not aware of the TPM's max size for extraData can inadvertently send a challenge that is too large.
This change introduces a HashNonce flag that uses the key's signing scheme hash algorithm to first hash the AttestOpts nonce. The server package also introduces the same logic to hash the nonce based on the Attestation message's AkPub signing scheme.
This allows verifiers to send an arbitrary amount of entropy without knowing the max hash size of the TPM.
Note: this may be a breaking change to users that don't populate AKPub within the attestation proto. This was never optional, and it was always populated by the go-tpm-tools client code.

Add HashNonce flag to Attest and VerifyAttestation
