google/go-tpm-tools

simulator/simulator.go
By moving the `s_failFunction` typecasting into a C helper function, `go-vet` no longer complains about a possible misuse of unsafe.Pointer. This also makes it clear that the name pointer is completely manged by the C code, preventing strange behavior from the garbage collector.
=> Fix go-vet warning

tpm2tools/keys.go, tpm2tools/template.go
Adds in a reasonable SRK template based on the TCG's guidance.
=> Introduce SRK Template

gotpm/cmd/pubkey.go, tpm2tools/keys.go, tpm2tools/keys_test.go, tpm2tools/seal_test.go, tpm2tools/template.go
Add SRK EK templates and seal test for ECC
=> Add SRK EK templates and gotpm pubkey support for ECC

gotpm/cmd/pubkey.go, gotpm/cmd/seal.go, gotpm/cmd/utils.go, gotpm/tests/seal_test.go
Depends on #31
Tests pass and manual invocations also succeed of real and virtual hardware.
=> Add Seal and Unseal Commands

.cirrus.yml
=> Add Cirrus CI Presubmits

Dockerfile
See https://github.com/google/go-tpm/pull/126#discussion_r322009896
=> Delete apt cache from Docker image

gotpm/cmd/seal.go, gotpm/cmd/seal_test.go, gotpm/cmd/utils.go, tpm2tools/keys.go, tpm2tools/pcr.go, tpm2tools/pcr_test.go
Update gotpm/cmd to support certify unseal.
=> Support certify for unseal in gotpm cmd

.cirrus.yml, Dockerfile, gotpm/cmd/pubkey.go, gotpm/cmd/root.go, gotpm/cmd/utils.go, tpm2tools/close.go, tpm2tools/import.go, tpm2tools/keys.go, tpm2tools/pcr_test.go, tpm2tools/seal_test.go, tpm2tools/signer.go, tpm2tools/template.go
This will check: formatting, style, imports, usage, etc...
=> cirrus: Use golangci-lint for presubmits

gotpm/cmd/root.go, gotpm/cmd/seal.go, server/import.go, tpm2tools/import.go, tpm2tools/keys.go, tpm2tools/pcr.go, tpm2tools/pcr_test.go
Added package comments for: `server`, `cmd`, `tpm2tools`
Import tpm2tools/proto as `tpmpb`
Fix the Protobuf copy bug
=> Add packages comments, fix Protobuf lints

server/import_test.go, tpm2tools/import.go
This is a breaking change, so we will need to release a 0.2 version
after this.
=> Import: Remove io.ReadWriter parameter

go.mod, go.sum
=> Update go-tpm-tools to 0.3.0

tpm2tools/signer.go, tpm2tools/signer_test.go
Fixes #86 CC: @chrisfenner, depends on #94 
Code, Tests, and Documentation for `SignData` have been added. Common code has been moved to a `getSignature` function.
`SignData` does the following:
- If the key is unrestricted, Go performs the hashing and passed the hash digest to `tpm2.Sign`
- If the key is restricted, we first call `tpm2.Hash` to get a hash ticket, then pass the ticket and digest to `tpm2.Sign`.
=> Add Key.SignData 

README.md
Address #83 
Link to MS TPM20 simulator instead of IBM SW simulator
=> Update README.md to correct simulator

client/close.go, internal/test_tpm.go, simulator/simulator.go
=> testing: Make sure to always close simulator on cleanup

.cirrus.yml, Dockerfile, proto/quote.go
Similar to https://github.com/google/go-tpm/pull/254
=> ci: Add lint task to run on Linux and Windows 

cel/cos_tlv.go, cel/cos_tlv_test.go, server/eventlog.go, server/eventlog_test.go, server/verify_test.go
Add parsing for more COS event types, converting them to Machine/ContainerState
Add parsing for ImageId, EnvVars and Args
=> Add parsing for more COS event types, to Machine/ContainerState

internal/test/test_tpm.go
This makes it possible for tests to depend on specific eventlogs when
testing attestation-based functionality. Specifically, we also want
to have this method inside of google3.
=> internal/test: add GetSimulatorWithLog

.github/workflows/ci.yml, simulator/internal/internal_cgo.go
=> Fix CGO warnings and add CI checks to prevent regression

cmd/go.mod, cmd/go.sum, go.work, go.work.sum, launcher/go.mod, launcher/go.sum
Following `RELEASING` instructions from #187 
=> Submodule update for v0.3.7

launcher/container-runner.service, launcher/container_runner.go
Output will appear in stdout as well.
=> Write the container output to both stdout/err and the logger

cloudbuild.yaml
ekcert and confidential space image licenses
=> Add licenses to the final image

launcher/agent.go, launcher/internal/verifier/client.go, launcher/internal/verifier/proto/service.proto, launcher/spec/launch_policy_test.go, launcher/spec/launcher_spec_test.go
Import protos with pb renaming and remove bad punctuation in
service.proto.
=> Fix golint issues and typos

.github/workflows/ci.yml, client/keys.go, go.mod, go.sum, go.work.sum
Added some attributes to the key structure for tpmDirect support along with related initialization. Fixed code style and cleaned up some comments.
=> Keys.go direct support

client/keys.go, client/pcr.go, client/pcr_direct_test.go, client/pcr_test.go, go.mod
Changed pcr.go to support direct and migrated all tests in pcr_test.go.
=> Migrated all PCR related functions to tpmDirect.

client/keys.go, go.work.sum
Implemented Session Encryption for Unseal.
=> Implemented Session Encryption

cloudbuild.yaml, launcher/image/test/README.md, launcher/image/test/cleanup.sh, launcher/image/test/create_vm.sh, launcher/image/test/data/cloud-init-config.yaml, launcher/image/test/test_cloud_init_userdata_disabled.sh, launcher/image/test/test_debug_cloudbuild.yaml, launcher/image/test/test_launcher_workload.sh, launcher/image/test/test_multiwriterpd_disabled.sh, launcher/image/test/test_startupscript_disabled.sh, launcher/image/test/util/read_serial.sh
Add a basic/smoke test which test some basic functionality of an image.
Update some scripts so they can take in args like vm name and zone.
Add a test to check user-data won't be executed in the hardened image.
=> Add/update tests for images/launcher

launcher/container_runner.go
Previously, the launcher formatted OCI env vars with its own logic (just concatentation of name, "=", and value). We update the launcher to have the same checks that are done on the server side.
=> Use same env var formatting logic on the launcher as server

cloudbuild.yaml, launcher/container_runner.go, launcher/image/cloudbuild.yaml, launcher/launcher/main.go
Add CS debug license:
projects/confidential-space-images/global/licenses/confidential-space-debug
Add proper log and doc for exitcode when launcher exits
Add AkCert present check before calling VerifyAttestation
=> Add proper debug license and logging to launcher

go.mod, go.sum
v0.5.0 and v0.5.1 had defects for hardware testing.
=> Import go-sev-guest v0.5.2

cloudbuild.yaml, launcher/container_runner.go, launcher/image/cloudbuild.yaml, launcher/image/test/test_debug_cloudbuild.yaml, launcher/image/test/test_debug_unstable_cloudbuild.yaml, launcher/image/test/test_hardened_cloudbuild.yaml, launcher/image/test/test_hardened_unstable_cloudbuild.yaml, launcher/image/test/test_ingress_network.yaml, launcher/image/test/test_launchpolicy_cloudbuild.yaml
Open ports using iptable based on the image config.
=> [launcher] Add capability to open ports

launcher/launcher/main.go
Add corsely check on filesystem setup (crypt and integrity) and tmpfs check based on OS command output.
=> [launcher] Verify FS and mount before launch

go.mod, go.sum
This fixes the GOARCH=386 build.
=> Update go-sev-guest to v0.7.0

launcher/container_runner.go
Instead of directly overwriting the token file (risking partial read race condition). Creating a tmp file first and then rename the tmp file to the token file.
=> [launcher] Update the token refresh logic

launcher/launcher/main.go
Fix the exit code on launcher. Improve error messages in the launcher main file.
=> [launcher] Fix launcher exit code

cmd/fake_attestation_server.go, cmd/fake_cloudlogging_server.go
a follow up on previous [PR #417](https://github.com/google/go-tpm-tools/pull/417)
=> add log replay comparisons in fake cloud logging server

server/policy_constants.go
https://github.com/google/go-tpm-tools/security/code-scanning/1
=> Fix an uint conversion

simulator/README.md
=> Update typo in README.md

launcher/agent/agent.go
Release lock if tpm attestation returns error, which will avoid potential deadlock.
=> Release lock if generating attestation returns error

launcher/agent/agent.go
Small fix to remove a duplicate error check
=> remove duplicate error check

launcher/internal/signaturediscovery/client.go, launcher/internal/signaturediscovery/client_test.go
We have flaky long lived because container launcher failed to fetch container signatures with 403 errors.
Looks like the detailed error message is swallowed by [pullTargetImage](https://github.com/google/go-tpm-tools/blob/5816a17931c753f5efbf5057ef74211c199af285/launcher/internal/signaturediscovery/client.go#L89) method where refreshing SA credentials first returns an error and then failover to fetching a public docker repo.
We should log the error message accordingly to determine what exactly went wrong.
=> Log detailed errors if refreshing SA credential goes wrong

launcher/container_runner.go, launcher/internal/experiments/experiments.go, launcher/internal/experiments/experiments_test.go
Removing a number of experiments that we would not consider rolling back.
=> Removed experiment flags that we would no longer consider rolling back

launcher/agent/agent.go, launcher/agent/agent_test.go
Adding a retry mechanism to fetch container signatures.
Given that we support "partial" errors from the GAV, I went with a fixed 300ms interval a max of 3 times. The goal of this retry is to handle transient errors.
Longer waits can be done, but in the interest of ODA tokens returning quickly, I decided to not allow this to wait more than a second for any 1 repo.
Happy to change that if needed.
=> Add retry to container signature fetch in agent

launcher/container_runner.go, launcher/image/test/test_mounts.yaml
Failed build off test-only commit:
https://pantheon.corp.google.com/cloud-build/builds;region=us-west1/c520701a-67d0-45e7-972b-8b1a46f465f8;step=15?inv=1&invt=Abcleg&project=confidential-space-images-dev
=> Override /dev/shm size only when specified

launcher/container_runner.go, launcher/internal/experiments/experiments.go, launcher/launcher/main.go, launcher/spec/launch_spec.go, launcher/spec/launch_spec_test.go
--The binary still needs to be updated.-- Until then, this feature will always be off. Which is fine ofc.
The binary has been updated and the flag exists.
=> Add tempfs experiment and gate mounting behind it

launcher/agent/agent.go, launcher/agent/agent_test.go, launcher/container_runner.go, launcher/container_runner_test.go, launcher/internal/experiments/experiments.go
Remove unused EnableSignedContainerCache + EnableMeasureMemoryMonitor from container launcher
=> Remove EnableSignedContainerCache + EnableMeasureMemoryMonitor from container launcher

cel/canonical_eventlog.go, cel/canonical_eventlog_test.go, cel/cos_tlv.go, cel/cos_tlv_test.go, go.mod, go.sum, go.work.sum, launcher/go.mod, launcher/go.sum, proto/attest.proto, proto/attest/attest.pb.go, server/eventlog.go, server/eventlog_test.go, server/verify.go, server/verify_test.go, verifier/go.mod, verifier/go.sum
CEL code was written based on TPM PCR. Now we want to support RTMR based CEL.
1. Add a new AppendEventRTMR to support rtmr CEL
=> Refactor CEL AppendEvent, to support RTMR

launcher/agent/agent.go
Launcher Attestation Agent now can support multiple Root of Trust.
Extend operation will extend measurements to all RoTs.
Attest will generate quote/report using a technology specific
RoT (like TDX RTMR), and fallback to use TPM if no such technology
specific RoT can be found.
=> [launcher] Allow multiple Roots of Trust in Agent

.github/workflows/ci.yml, client/attest.go, client/attest_network_test.go, client/attest_test.go, go.work.sum, internal/cert.go, internal/cert_test.go, internal/test/test_cert.go, launcher/agent/agent.go, launcher/agent/agent_test.go, launcher/cloudbuild.yaml, launcher/go.mod, verifier/client.go, verifier/fake/fakeverifier.go, verifier/oci/cosign/fakesignature.go, verifier/rest/rest.go
merging rtmr branch to main.
cs main image starts to based on cos-tdx-113-lts which will be used for both sev and tdx.
=> merge tdx_rtmr to main

launcher/internal/experiments/experiments.go
=> Add privileged cs experiment flag

launcher/container_runner.go, launcher/container_runner_test.go, launcher/launcher/main.go
Non root workload should be able to access the directory. 0744 doesn't include the execute permission for non root user. Change it to 0755
=> [launcher] Update cs host directory permission

verifier/rest/rest.go
w/o alias added to proto buffer imports has increased burdens to backporting to G3. Furthermore, this violates the golang style guide go/go-style/best-practices#import-protos.
=> Add alias to proto buffer and remove extra imports

.github/workflows/releaser.yaml
* Remove write permission for the token
=> Update releaser config so it won't run on a PR

launcher/internal/experiments/experiments.go, launcher/internal/experiments/experiments_test.go
Adds an experiment flag for the VerifyCS experiment.
=> Add VerifyCS experiment flag

verifier/rest/rest.go
Remove duplicated TpmAttestation init
=> Remove duplicated code in rest verifier
